### ISSUE TITLE
Console errors - React usage

### ISSUE THREAD

**Issue by gaeljacquin** [TakingITGlobal/a11ize#5]
#### Description
I followed the instructions for React usage and while the toolkit is functional, it returns the following errors in the console:

```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `d`, expected a single ReactElement.
    in d (created by _)
    in _ (at src/index.js:9)
```

```
Warning: An effect function must not return anything besides a function, which is used for clean-up.

It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:

useEffect(() => {
  async function fetchData() {
    // You can await here
    const response = await MyAPI.getData(someId);
    // ...
  }
  fetchData();
}, [someId]); // Or [] if effect doesn't need props or state

Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching
    in _ (at src/index.js:9)
```    

I installed it on my website and the following 3 example projects from the [React official website](https://reactjs.org/community/examples.html): **Calculator**, **Emoji Search**, and **Snap Shot**. The only difference is I'm not getting the second error on my website.

#### Screenshots
![1 - mysite](https://user-images.githubusercontent.com/8724132/103155153-ecce9880-476a-11eb-843f-40d9d81284f7.png)
---
![2 - snapshot](https://user-images.githubusercontent.com/8724132/103155163-fc4de180-476a-11eb-8228-c886ae7093e9.png)
---
![3 - calculator](https://user-images.githubusercontent.com/8724132/103155164-fce67800-476a-11eb-905e-000797a7d4dc.png)
---
![4 - emoji-search](https://user-images.githubusercontent.com/8724132/103155165-fce67800-476a-11eb-8fee-27ff9ca150de.png)

#### To Reproduce
Import the component into `index.js` or `App.js` and wrap the content with `A11yWrapper`.

```
...
import A11yWrapper from "@takingitglobal/a11ize"


ReactDOM.render(<A11yWrapper><App /></A11yWrapper>, document.getElementById("root"));
```

```
...
import A11yWrapper from "@takingitglobal/a11ize"

class App extends Component {
  ...
   
  render() {
    return (
      <A11yWrapper>
       ...
      </A11yWrapper>
    );
  }
}

export default App;

```

**Comment by davidli3100** [comment]
Hi! There's a known issue with React right now - we're working on getting it fixed (hopefully tomorrow if we're all not busy).

**Comment by jhthenerd** [comment]
The issue seems to be solved as of the current release, so I'll go ahead and close this. If you're still experiencing the same issue, feel free to re-open it.
