### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by gaeljacquin** [TakingITGlobal/a11ize#8]
How do I set it up in an existing React app for local development?

**Comment by davidli3100** [comment]
`yarn add @takingitglobal/a11ize` or `npm install` depending on which package manager you're using. 

Then you simply import `A11yWrapper` and wrap whatever components you'd want to be accessible with the `A11yWrapper` component.

Generally you'd just put the `A11yWrapper` over the entire app

**Comment by gaeljacquin** [comment]
I'm able to install it as described in the README. I meant set it up to fix bugs or add new features, then publish the changes locally and test them in an existing React app.

So far I've only been able to run the `storybooks` scripts after installing `react` & `react-dom` as dev dependencies directly in the source folder, when I was updating the translations.

**Comment by davidli3100** [comment]
Oh I see what you mean - if you clone the repo and run `yarn install` to install all the dependencies, you should then be able to build a11ize using webpack, or start up a storybook server to demo with

**Comment by davidli3100** [comment]
The storybook is essentially the React app (see `A11yWrapper.stories.js`) in `components` and you can test any changes you make there

**Comment by gaeljacquin** [comment]
The storybook server should do; I'm able to make some changes and see them right away. Thanks.
